services:
  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ycbetterdb
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ycbetter_network

networks:
  ycbetter_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local